apiVersion: v1
kind: ServiceAccount
metadata:
  name: bookwarehouse
  namespace: {{ .Values.namespace }}
---
apiVersion: v1
kind: Service
metadata:
  name: bookwarehouse
  namespace: {{ .Values.namespace }}
  labels:
    app: bookwarehouse
spec:
  ports:
  - port: 80
    name: bookwarehouse-port
  selector:
    app: bookwarehouse
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookwarehouse
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookwarehouse
  template:
    metadata:
      labels:
        app: bookwarehouse
        version: v1
    spec:
      serviceAccountName: bookwarehouse
      containers:
        - name: bookwarehouse
          image: openservicemesh/bookwarehouse:v0.2.0
          imagePullPolicy: Always
          command: ["/bookwarehouse"]