apiVersion: v1
kind: ServiceAccount
metadata:
  name: bookbuyer
  namespace: {{ .Values.namespace }}
---
apiVersion: v1
kind: Service
metadata:
  name: bookbuyer
  namespace: {{ .Values.namespace }}
  labels:
    app: bookbuyer
spec:
  ports:
  - port: 9999
    name: dummy-unused-port
  selector:
    app: bookbuyer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookbuyer
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookbuyer
      version: v1
  template:
    metadata:
      labels:
        app: bookbuyer
        version: v1
    spec:
      serviceAccountName: bookbuyer
      containers:
        - name: bookbuyer
          image: openservicemesh/bookbuyer:v0.2.0
          imagePullPolicy: Always
          command: ["/bookbuyer"]
          env:
            - name: "BOOKSTORE_NAMESPACE"
              value: {{ .Values.namespace }}
            - name: "BOOKSTORE_SVC"
              value: bookstore