apiVersion: apps/v1
kind: Deployment
metadata:
  name: policy-deploy-ok
spec:
  selector:
    matchLabels:
      app: policy-deploy-ok
  replicas: 1
  template:
    metadata:
      labels:
        app: policy-deploy-ok
        release-type: test
    spec:
      containers:
      - name: container
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | toString }}"
        ports:
          - containerPort: 3000
        resources:
          requests:
            cpu: 10m
            memory: 8Mi
          limits:
            cpu: 50m
            memory: 64Mi

