apiVersion: apps/v1
kind: Deployment
metadata:
  name: opentelemetry-app1
  labels:
    app: opentelemetry-app1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: opentelemetry-app1
  template:
    metadata:
      labels:
        app: opentelemetry-app1
    spec:
      containers:
        - name: opentelemetry-app1
          image: "{{ .Values.repository }}:{{ .Values.tag | toString }}"
          ports:
            - containerPort: 8080
          env:
            - name: APP_NAME
              valueFrom:
                fieldRef:
                  fieldPath: "metadata.labels['app']"
            - name: APPINSIGHTS_INSTRUMENTATION_KEY
              value: {{ .Values.appin_key }}
            - name: REMOTE_ENDPOINT
              value: "http://opentelemetry-app2:8080/data"
          resources:
            requests:
                cpu: 10m
                memory: 16M
            limits:
                cpu: 100M
                memory: 128M
       