apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
  name: ai-ingress
spec:
  rules:
    - host: {{ .Values.baseurl }}
      http:
        paths:
          - path: /api/customvision/
            backend:
              serviceName: customvision-api
              servicePort: 80
          - path: /api/
            backend:
              serviceName: face-api
              servicePort: 80
          - path: /
            backend:
              serviceName: swagger
              servicePort: 80