apiVersion: apps/v1
kind: Deployment
metadata:
  name: podinfo
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      app: podinfo
  template:
    metadata:
      labels:
        app: podinfo
    spec:
      containers:
      - name: podinfo
        image: "stefanprodan/podinfo:latest"
        ports:
        - containerPort: 8080
        command:
            - ./podinfo
            - --port=8080
            - --level=debug
        resources:
          requests:
            cpu: 10m
            memory: 16M
          limits:
            cpu: 100m
            memory: 64M