apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-spa
  labels:
    app: {{ template "name" . }}-spa
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.appspa.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "name" . }}-spa
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "9113"
      labels:
        app: {{ template "name" . }}-spa
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}-spa
          image: "{{ .Values.appspa.image.repository }}:{{ .Values.appspa.image.tag | toString }}"
          imagePullPolicy: {{ .Values.appspa.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.appspa.service.internalPort }}
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.appspa.service.internalPort }}
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.appspa.service.internalPort }}
          resources:
{{ toYaml .Values.appspa.resources | indent 12 }}
        - name: adapter
          image: nginx/nginx-prometheus-exporter:0.6.0
          args: ["-nginx.scrape-uri","http://localhost:8080/status"]
          ports:
          - containerPort: 9113
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
      {{- if .Values.appspa.imagePullSecrets }}
      imagePullSecrets:
        - name: {{ .Values.appspa.imagePullSecrets }}
      {{- end }}
