apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-gen
spec:
  replicas: {{ .Values.appgen.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "name" . }}-gen
  template:
    metadata:
      labels:
        app: {{ template "name" . }}-gen
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}-gen
          image: "{{ .Values.appgen.image.repository }}:{{ .Values.appgen.image.tag | toString }}"
          imagePullPolicy: {{ .Values.appgen.image.pullPolicy }}
          env:
          - name: FQDN
            value: {{ .Values.apphost }}
          resources:
{{ toYaml .Values.appgen.resources | indent 12 }}
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
      {{- if .Values.appgen.imagePullSecrets }}
      imagePullSecrets:
        - name: {{ .Values.appgen.imagePullSecrets }}
      {{- end }}
