apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-retry
  labels:
    app: {{ template "name" . }}-retry
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "name" . }}-retry
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "name" . }}-retry
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}-retry
          image: "tkubica/retry-backend"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80