apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-todo
  labels:
    app: {{ template "name" . }}-todo
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.apptodo.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "name" . }}-todo
      release: {{ .Release.Name }}
      aadpodidbinding: secrets-reader
  template:
    metadata:
      labels:
        app: {{ template "name" . }}-todo
        release: {{ .Release.Name }}
        aadpodidbinding: secrets-reader
    spec:
      containers:
        - name: {{ .Chart.Name }}-todo
          image: "{{ .Values.apptodo.image.repository }}:{{ .Values.apptodo.image.tag | toString }}"
          imagePullPolicy: {{ .Values.apptodo.image.pullPolicy }}
          volumeMounts:
          - name: keyvault
            mountPath: /keyvault
            readOnly: true
          ports:
            - containerPort: {{ .Values.apptodo.service.internalPort }}
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.apptodo.service.internalPort }}
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.apptodo.service.internalPort }}
          resources:
{{ toYaml .Values.apptodo.resources | indent 12 }}
      volumes:
        - name: keyvault
          flexVolume:
            driver: "azure/kv"
            options:
              usepodidentity: "true"       
              keyvaultname: {{ .Values.keyvault.name }}             
              keyvaultobjectnames: {{ .Values.keyvault.key }}       
              keyvaultobjecttypes: secret  
              tenantid: {{ .Values.keyvault.tenant }}       
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
      {{- if .Values.apptodo.imagePullSecrets }}
      imagePullSecrets:
        - name: {{ .Values.apptodo.imagePullSecrets }}
      {{- end }}
