apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: client
spec:
  selector:
    matchLabels:
      app: client
  serviceName: client
  replicas: 1
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - name: container
        image: tkubica/mybox
        resources:
          requests:
            cpu: 10m
            memory: 16M
          limits:
            cpu: 100M
            memory: 128M
