apiVersion: azure.microsoft.com/v1alpha1
kind: StorageAccount
metadata:
  name: tomasdemostorage123
spec:
  location: westeurope
  resourceGroup: aks
  sku:
    name: Standard_LRS
  kind: StorageV2
  accessTier: Hot
  supportsHttpsTrafficOnly: true
# Optional: networkRule
  # networkRule:
  #   bypass: AzureServices # Possible values are AzureServices, Metrics, None, Logging
  #   defaultAction: Deny # Possible values are Allow, Deny
  #   virtualNetworkRules: 
  #     - subnetId: /subscriptions/{subscription}/resourceGroups/{resourcegroup}/providers/Microsoft.Network/virtualNetworks/{vnet}/subnets/{subnet}
  #   ipRules: #could be an ip range or a ip address
  #     - ipAddressOrRange: 2.2.0.0/24
  #     - ipAddressOrRange: 2.2.2.1