apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-azuredisk-clone
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: managed-csi-standard-ssd
  dataSource:
    kind: PersistentVolumeClaim
    name: pvc-azuredisk
---
kind: Pod
apiVersion: v1
metadata:
  name: nginxClone
spec:
  containers:
    - image: nginx
      name: nginx
      command:
        - "/bin/sh"
        - "-c"
        - nginx & while true; do echo $(date) >> /usr/share/nginx/html/index.html; sleep 1; done
      volumeMounts:
        - name: azuredisk
          mountPath: "/usr/share/nginx/html"
  volumes:
    - name: azuredisk
      persistentVolumeClaim:
        claimName: pvc-azuredisk-clone