apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-azuredisk-raw
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeMode: Block
  storageClassName: managed-csi-standard-ssd