kind: Pod
apiVersion: v1
metadata:
  name: pod-pvc-disk
spec:
  containers:
    - name: ubuntu
      image: tutum/curl
      command: ["tail"]
      args: ["-f", "/dev/null"]
      volumeMounts:
      - mountPath: "/mnt/azure"
        name: volume
      resources:
        limits:
          cpu: 100m
          memory: 128M
  volumes:
    - name: volume
      persistentVolumeClaim:
        claimName: pvc-azuredisk