kind: Pod
apiVersion: v1
metadata:
  name: nginx
spec:
  containers:
    - image: nginx
      name: nginx
      command:
        - "/bin/sh"
        - "-c"
        - nginx & while true; do echo $(date) >> /usr/share/nginx/html/index.html; sleep 1; done
      volumeMounts:
        - name: azurefile
          mountPath: "/usr/share/nginx/html"
  volumes:
    - name: azurefile
      persistentVolumeClaim:
        claimName: pvc-azurefile