apiVersion: snapshot.storage.k8s.io/v1beta1
kind: VolumeSnapshot
metadata:
  name: azurefile-volume-snapshot1
spec:
  volumeSnapshotClassName: csi-azurefile-vsc
  source:
    persistentVolumeClaimName: pvc-azurefile