apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: managed-csi-standard-ssd
provisioner: disk.csi.azure.com
parameters:
  skuname: StandardSSD_LRS
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true