apiVersion: apps/v1
kind: Deployment
metadata:
  name: oc-tfgen
  labels:
    app: oc-tfgen
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oc-tfgen
  template:
    metadata:
      labels:
        app: oc-tfgen
    spec:
      containers:
        - name: oc-tfgen
          image: tkubica/mybox
          command: ["bash"]
          args: ["-c", "while true; do curl -s oc-app1:8080; sleep $(( $RANDOM % 60 )); curl -s oc-app2:8080; sleep $(( $RANDOM % 60 )); done"]
          resources:
            requests:
                cpu: 10m
                memory: 16M
            limits:
                cpu: 100M
                memory: 128M
       