apiVersion: apps/v1
kind: Deployment
metadata:
  name: oc-app1
  labels:
    app: oc-app1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: oc-app1
  template:
    metadata:
      labels:
        app: oc-app1
    spec:
      containers:
        - name: oc-app1
          image: "{{ .Values.repository }}:{{ .Values.tag | toString }}"
          ports:
            - containerPort: 8080
          env:
            - name: SERVICE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: "metadata.labels['app']"
            - name: COLLECTOR
              value: {{ .Values.collector }}
            - name: REMOTE_ENDPOINT
              value: "http://oc-app2:8080/data"
          resources:
            requests:
                cpu: 10m
                memory: 16M
            limits:
                cpu: 100M
                memory: 128M
       